runtime: nodejs22
version: 

automatic_scaling:
  max_instances: 10

env_variables:
  NODE_ENV: production
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  PHYSICAL_MAILING_ADDRESS: "NASA Goddard Space Flight Center\nAstrophysics Science Division, Code 660\n8800 Greenbelt Road\nGreenbelt, MD 20771"
